name: Hello Github Actions
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Job triggered by a ${{ github.event_name }} event"
      - run: echo "ğŸ§ Job is now running on ${{ runner.os }}"
      - run: echo "ğŸ” Branch is ${{ github.ref }}"
      - run: echo "ğŸ” Repo is ${{ github.repository }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ Repo has been cloned to the runner"
      - run: echo "ğŸ–¥ï¸ Workflow is ready"
      - name: List files in the repo
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ Job's status is ${{ job.status }}"
